# To create a development.yaml file, please replace xxx with actual values.

env: development
url: http://localhost:8080
port: 8080
reset_password_timeout: 60 # 1 minute, should be at least 60 minutes in production
page_size: 10
tags_limit: 10
login_attempts_limit: 3 # number of attempts before applying login_attempts_timeout
login_attempts_timeout: 60 # 1 minute, should be at least 15 minutes in production
email_from: MCCS localhost dev
daily_email_schedule: "* * 1 * * *"
balance_check_schedule: "* * 1 * * *"
concurrency_num: 3
receive_trade_contact_emails: true
receive_signup_notifications: true

validate:
  email:
    maxLen: 100
  password:
    minLen: 8

transaction:
  maxNegBal: 0
  maxPosBal: 500

psql:
  host: postgres
  port: 5432
  user: postgres
  password:
  db: mccs

mongo:
  url: mongodb://mongo:27017
  database: mccs

es:
  url: http://es01:9200

jwt:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    xxx
    -----END RSA PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    xxx
    -----END PUBLIC KEY-----

sendgrid:
  key: xxx
  sender_email: xxx
