env: test
url: http://localhost:8080
port: 8080
reset_password_timeout: 60
page_size: 10
tags_limit: 10
login_attempts_limit: 3
login_attempts_timeout: 900
email_from: MCCS
daily_email_schedule: "0 0 7 * * *"
balance_check_schedule: "0 0 * * * *"
concurrency_num: 3
receive_trade_contact_emails: true
receive_signup_notifications: true

rate_limiting:
  duration: 1 # minute
  requests: 1000

validate:
  email:
    maxLen: 100
  password:
    minLen: 8

transaction:
  max_neg_bal: 0
  max_pos_bal: 500

psql:
  host: postgres
  port: 5432
  user: postgres
  password:
  db: mccs

mongo:
  url: mongodb://mongo:27017
  database: mccs

redis:
  host: redis
  port: 6379
  password: sOmE_sEcUrE_pAsS

es:
  url: http://es01:9200

jwt:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    xxx
    -----END RSA PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    xxx
    -----END PUBLIC KEY-----

sendgrid:
  key: xxx
  sender_email: xxx
